export default {
    GET_MOVIES_LIST_SUCCES: 'GET_MOVIES_LIST_SUCCES',
    LOADER_UP: 'LOADER_UP',
    LOADER_DOWN: 'LOADER_DOWN',
    GET_MORE_MOVIES_SUCCES: 'GET_MORE_MOVIES_SUCCES',
    SET_NO_DATA: 'SET_NO_DATA',
    SET_NO_MORE_DATA: 'SET_NO_MORE_DATA'
};